In [1]:
import os
import json
import pandas as pd
import random

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

## **Load OOS Data**

Out-of-Scope sentences taken from CLINC150 dataset.  
https://github.com/clinc/oos-eval.git

In [3]:
!git clone https://github.com/clinc/oos-eval.git

Cloning into 'oos-eval'...
remote: Enumerating objects: 69, done.
remote: Counting objects: 100% (19/19), done.
remote: Compressing objects: 100% (3/3), done.
remote: Total 69 (delta 16), reused 16 (delta 16), pack-reused 50 (from 1)
Receiving objects: 100% (69/69), 1.74 MiB | 15.25 MiB/s, done.
Resolving deltas: 100% (35/35), done.

In [4]:
data_path = os.path.join('oos-eval', 'data')

In [5]:
with open(os.path.join(data_path, 'data_full.json'), 'r') as f:
  data = json.load(f)

In [6]:
all_sentences = []
for key, val in data.items():
  for entry in val:
    all_sentences.append(entry[0])

## **Load Intent Classification Data**

In [7]:
os.chdir('/content/drive/MyDrive/FYP')

In [8]:
DATA_PATH = os.path.join("intent_data.csv")

In [9]:
# load necessary columns into df
df = pd.read_csv(DATA_PATH, usecols=['question', 'intent'])
df.head()

           intent                                        question
0  part_of_speech                Is īnfrēnā a proper name or not?
1  part_of_speech                       What POS is adprobātūrum?
2  part_of_speech  Is carnārium used as a verb or something else?
3  part_of_speech                Is augurātiōnibus a noun or not?
4  part_of_speech              Part of speech for synodontītidum?

In [10]:
# dataset summary
print(f"Dataset size: {len(df)} rows")
print(f"Intents: {df['intent'].value_counts().to_dict()}")

Dataset size: 1100 rows
Intents: {'part_of_speech': 100, 'person': 100, 'mood': 100, 'tense': 100, 'voice': 100, 'aspect': 100, 'number': 100, 'case': 100, 'gender': 100, 'declension': 100, 'conjugation': 100}

## **Extend Dataset with OOS Sentences**

In [11]:
# select subset of sentences to be added
n = 70
sentences = random.sample(all_sentences, n)

In [12]:
# Create a new dataframe from the list
new_df = pd.DataFrame({
    'question': sentences,
    'intent': ['oos'] * len(sentences)
})

new_df.head()

                                            question intent
0                            tell me how you've been    oos
1  is cleaning the kitchen coming up on my list o...    oos
2      i need to take out the trash please remind me    oos
3                               i need a spider fact    oos
4                              your speech slower it    oos

In [13]:
# Append oos sentences to original dataframe
df = pd.concat([df, new_df], ignore_index=True)

In [14]:
print(df.tail())
print(df['intent'].value_counts())

     intent                                           question
1165    oos       what kind of plug type do they use in russia
1166    oos  what are the best family restaurants in charlo...
1167    oos      i need to know when my mastercard will expire
1168    oos           what's my current limit on my mastercard
1169    oos  what is the lowest amount i can pay for my car...
intent
part_of_speech    100
person            100
mood              100
tense             100
voice             100
aspect            100
number            100
case              100
gender            100
declension        100
conjugation       100
oos                70
Name: count, dtype: int64

In [15]:
# save to file
df.to_csv("data_with_oos.csv", index=False)